// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-wCY0Y8IP78igIWm_yNU-eRyzpAOYDY',
    appId: '1:803901681645:web:fb8cbc8a7ba7da787a01e4',
    messagingSenderId: '803901681645',
    projectId: 'flutter-auth-app-8fc44',
    authDomain: 'flutter-auth-app-8fc44.firebaseapp.com',
    storageBucket: 'flutter-auth-app-8fc44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTZMLETV38lon5GjL7pJXcMg6l7TcLX4',
    appId: '1:803901681645:android:d8ce72130fedb8657a01e4',
    messagingSenderId: '803901681645',
    projectId: 'flutter-auth-app-8fc44',
    storageBucket: 'flutter-auth-app-8fc44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ZSETbEh7H6DH25E4D23CIQJ3WQpgUn4',
    appId: '1:803901681645:ios:3eb177a20726cd497a01e4',
    messagingSenderId: '803901681645',
    projectId: 'flutter-auth-app-8fc44',
    storageBucket: 'flutter-auth-app-8fc44.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
